# Generated by Django 2.1 on 2018-11-18 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('descripcion', models.TextField()),
                ('foto', models.CharField(max_length=300)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre', models.CharField(max_length=100)),
                ('tiempo_ganador', models.CharField(max_length=100)),
                ('ganador', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha', models.DateField(null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='campeonato.Campeonato')),
                ('info_pista', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='premio', to='premio.InfoPista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
