# Generated by Django 2.1 on 2018-10-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('descripcion', models.TextField()),
                ('foto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuderia', to='campeonato.Campeonato')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
