# Generated by Django 2.1 on 2018-11-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('beam_wing', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('end_plate', models.CharField(max_length=300)),
                ('foto', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=300)),
                ('motor', models.CharField(max_length=300)),
                ('ponton', models.CharField(max_length=300)),
                ('potencia', models.CharField(max_length=300)),
                ('modelo', models.CharField(max_length=300)),
                ('escuderia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autos', to='escuderia.Escuderia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
