# Generated by Django 2.1 on 2018-10-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
        ('escuderia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='piloto', to='auto.Auto')),
                ('escuderia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piloto', to='escuderia.Escuderia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
